### ISSUE TITLE
crash on startup on macOS Sierra 10.12.6 (16G1036)

### ISSUE THREAD

**Issue by lampie73** [ETCLabs/OSCRouter#11]
Hi all,
unfortunately for me latest version crashes for me. I posted the Apple crash report here. https://pastebin.com/Y9ev8xWu
Let me know if you need anything else.

**Comment by MizPlusPlus** [comment]
Thank you very much for the report; should be fixed in build 9!

**Comment by hinrichsenhans** [comment]
Closing - likely fixed in 6fa8c43. Let us know if it comes up again!
