### ISSUE TITLE
Does OSCRouter forward non-OSC Packets?

### ISSUE THREAD

**Issue by mikewoodld** [ETCLabs/OSCRouter#26]
The tooltip seems to imply that it does:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/13637288/168441563-4e065ce8-ec34-4eab-baef-3ced76c5ca36.png">

But in practice, I'm seeing an incoming ICMP ping coming in the input side but not going out the output side.

**Comment by mikewoodld** [comment]
To clarify, I see the little white icon light up every time the ping comes in, but the output side doesn't light up and the packet is not being forwarded.

**Comment by mikewoodld** [comment]
bump bump! @sammysmallman @dmeltzer @samkearney

**Comment by MizPlusPlus** [comment]
This should work, I'll take a look 🤙

**Comment by mikewoodld** [comment]
Thanks, Chris!

**Comment by MizPlusPlus** [comment]
Okay, I see a bug.  Can you also send a trivial route that isn't working for you, so that I can test it specifically. Thanks 🙏

**Comment by MizPlusPlus** [comment]
Give the updated version a try, and let me know if anything is not working

**Comment by mikewoodld** [comment]
Thanks! I'll give it a try soon when I'm back with the gear and report back.

**Comment by mikewoodld** [comment]
@MizPlusPlus seems like this fixed the issue! Thank you! 

And for folks reading in the future, this wasn't actually a ping, it was a UDP packet (but still non-osc) - not sure why Wireshark had originally categorized it as IMCP but regardless, the issue is fixed!
