### ISSUE TITLE
Remove arguments from output path

### ISSUE THREAD

**Issue by odisfm** [ETCLabs/OSCRouter#29]
I would like to strip the first argument from an OSC address while leaving the rest of the address intact. For instance I might have the input path as:

/resolume/composition/layers/10/clips/3/connect

I want the output to be:

/composition/layers/10/clips/3/connect

I know I can do /%2/%3/%4/%5/%6/%7 for the output, but this doesn't work if I have an input with more or less than 7 arguments in a path. maybe the syntax would be something like /%2/* 

love this tool by the way!!

**Comment by MizPlusPlus** [comment]
Hey [odisfm](https://github.com/odisfm),

I've just publish a new release with scripting support - check it out 👍
