### ISSUE TITLE
Suggestion: Modify icon to better reflect app purpose and remove confusion with EOS app

### ISSUE THREAD

**Issue by calwalker1** [ETCLabs/OSCRouter#30]
Hi All,
I like this program but the usage of the generic ETC Logo means if you have both the EOS app and OSCRouter app running on your computer at the same time it is confusing which app is which.

I don't know if anyone is open to the logo being changed to better reflect the app's purpose. I have taken the existing ICON and removed the "ETC" text replacing it with a shuffle icon which was sourced from FontAwesome which lists this particular icon as CC with attribution. I am not familiar enough with licensing to know where or how we attribute it?
This also means we are modifying the ETC logo which is likely protected by some form of copyright so this is more complex. I am happy to hear any suggestions and thoughts.

<img width="549" alt="image" src="https://github.com/user-attachments/assets/babcd6a7-ac88-467b-b050-66ef12f3e917">

**Comment by MizPlusPlus** [comment]
Hey [calwalker1](https://github.com/calwalker1),

I've published a new release with a different icon 👍
